version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        depends_on:
            - php
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./html:/var/www/html
        environment:
            - NGINX_PORT=80
    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=0000
            - MYSQL_DATABASE=database
    php:
        image: php:7.2.6-fpm-alpine
        depends_on:
            - db
        volumes:
            - ./html:/var/www/html
        environment:
            - DATABASE_HOST=db
            - MYSQL_ROOT_PASSWORD=0000
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            - PMA_HOST=db
volumes:
    db-data:
