version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./html:/var/www/html
        environment:
            - NGINX_PORT=80
